# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_html_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statichtml',
            name='markdown',
            field=models.TextField(default=''),
        ),
    ]
